### ISSUE TITLE
How Serializer Struture to Session

### ISSUE THREAD

**Issue by Bernardoow** [yesodweb/yesod-cookbook#46]
Hi !!

I'm newbi with haskell and I did a project that I needed put the data into the session.

So,

setSession "game"  ((toStrict $ encodeToLazyText $ (Game Nothing Nothing)) :: Text)

`data Position = Position 
    { posX :: Int
    , posY :: Int   
    }   
    deriving (Show, Eq)

instance FromJSON Position where
    parseJSON = withObject "Position" $ \v -> Position
        <$> v .: "posX"
        <*> v .: "posY"

instance ToJSON Position where
  toJSON (Position posX posY) = object ["posX" .= posX, "posY" .= posY]

  toEncoding (Position posX posY) = pairs ("posX" .= posX <> "posY" .= posY)

data Game = Game 
    { manPosition :: Maybe Position
    , dinosaurPosition :: Maybe Position
    }
    deriving Show

instance ToJSON Game where
  toJSON (Game manPosition dinosaurPosition) = object ["manPosition" .= manPosition, "dinosaurPosition" .= dinosaurPosition]

  toEncoding (Game manPosition dinosaurPosition) = pairs ("manPosition" .= manPosition <> "dinosaurPosition" .= dinosaurPosition)

instance FromJSON Game where
    parseJSON = withObject "Game" $ \v -> Game
        <$> v .: "manPosition"
        <*> v .: "dinosaurPosition"`

To put in session I used this:

{-# LANGUAGE NoImplicitPrelude #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE ViewPatterns #-}

import Data.Aeson.Text (encodeToLazyText)

 setSession "game"  ((toStrict $ encodeToLazyText $ (Game Nothing Nothing)) :: Text)

and to transform to structure I used 

import Data.Aeson (decode)
decode $ TL.encodeUtf8 $ fromStrict gameSession :: Maybe Game

**It can be transformed to cookbook?**

**Comment by psibi** [comment]
Sure, that would be helpful. Thanks!

**Comment by Bernardoow** [comment]
#47
