### ISSUE TITLE
Can yesod handle a massive commercial site?

### ISSUE THREAD

**Issue by JohnReedLOL** [yesodweb/yesod-cookbook#6]
Dear yesod,

I was wondering if you could handle a massive commercial website. 

SoundCloud and AirBnB use Rails, Bitbucket was built with Djengo, LinkedIn uses Play framework, PayPal uses Node.js. Seeing big companies use a framework is very reassuring, but what was built with yesod? http://lambdacms.org/ ? That's hardly an enterprise grade application on the order of PayPal, AirBnB, or SoundCloud.

Is yesod fit to handle a website like SoundCloud or PayPal? 

On that note, can I deploy yesod in such a way that it can expand quickly and automatically to withstand huge, unexpected onslaughts of traffic? I'm talking from a few thousand users streaming content and interacting with the server to hundreds of thousands of users and then back down to a few thousand in a matter of hours?

p.s. I don't care that much about performance because IO is the bottleneck, I care about scalability.

**Comment by erikd** [comment]
I have not done anything that is anywhere near the size of SoundCloud or PayPal.

I have however done a large internal webapp at work that collects data from elsewhere for display as well as retrieval via a JSON API. There are a couple of bots written in Python and Ruby that hammer on this API. Even when being hammered by a number of bots simultaneously, the Yesod webapp can provide data to the clients faster than the clients can process it.

In general, a real world Yesod webapp will handle a much higher load than a webapp written in Python or Ruby, mainly because Haskell's concurrency story is so much stronger that either Python or Ruby. Yesod makes full use of the concurrency provided by Haskell's RTS (Run Time System).

AFAIAC, a few thousand users streaming audio is a relatively small load. My guesstimate is that would be easily handled by a machine with 4 cores.

**Comment by JohnReedLOL** [comment]
So here's what I'm doing...

https://www.reddit.com/r/SexPositive/comments/4611ug/porn_site_for_women_nonstraight_male_porn/

^ It's a universal porn site for the non-straight male audiences of the world. It's supposed to fill a void that the straight male porn sites have failed to fill.

Here are my concerns. If I use Rails, I can just deploy to Heroku and it will scale automatically. If the load starts very small and then all of a sudden starts increasing exponentially, heroku can grow a rails app. I don't know if heroku can grow a yesod app. And if I am going to be providing pornography to the straight women, lesbian women, etc. of the world I am going to need to scale. Frequently.

**Comment by erikd** [comment]
Sure "just deploy to Heroku" and spend far more CPU hours and money that you would need to with Haskell.

Streaming videos should mostly just consist of decode the request and call down the the Linux kernel's `sendfile` syscall (see `man sendfile`). I don't know how easy it is to access `sendfile` from a Rails app, but I know its supported in Yesod on Linux. Once you are streaming video using `sendfile` everything is being done in the Linux kernel.

Thinking about this some more, your webapp is basically has two parts:
- Standard webapp login, search, menu, user management, farm stream requests to streaming component.
- Streaming selected videos.

There is absolutely no reason why they have to be the same technology. The streaming videos part is easy to scale, just add more machines. The webapp part is is much less data intensive and much less likely to need to be scaled. Its probably also much more difficult to scale. Using Haskell/Yesod for that makes it much less likely that this bit would ever _need_ to run on more than one machine. 

Even if your website becomes hugely successful, the vast bulk of all data handled/transferred/processed etc is the video data.

There is however some information in the Yesod book about front end load balancers: http://www.yesodweb.com/book/deploying-your-webapp

**Comment by JohnReedLOL** [comment]
Umm... they way I was thinking of doing it is using Amazon S3 for the content files, Amazon video transcoder for converting 1080p mp4 file to 480p mp4 file. I thought that if the video file is on Amazon S3 you could just specify the URL of the Amazon S3 file in the <video> tag in HTML5 and the web page will just stream from the Amazon S3 file directly.

The thing is due to the humongous amounts of copyright infringement, videos have to be given a logo or brand so that even if they are stolen they will still have the website name on the video. This effectively amounts to the user first uploading the file, then the web server using something like ffmpeg or audacity to process it before sending it to Amazon S3 input bucket, running the transcoder, and finally streaming from the Amazon S3 output bucket. Running ffmpeg and audacity with a couple hundred videos and mp3 files could get a little heavy, especially since I have to first mass import "seed content" from creative commons sources before the real user end content starts coming in.

For search, because I just have a list of contents that are independent of one another and searchable based on title, keyword, and full text description, I was thinking of using Amazon elastic-search cluster. Elastic search has a rest API so I wouldn't need an SQL database - just parse the json and do callbacks. 

It would be nice to just require everyone to sign in with a google account, but a lot of people are unwilling to do so because they think it openID will associate their work email with stuff that is not appropriate for work. I guess I could use elasticsearch for the usernames and passwords and user preferences too.

For user management and content management I can just use the REST API to delete content or users or the website can do it automatically.

The fact that the webapp part has to do audio and video processing is a little bit concerning because that significantly adds to the load on the web server. I mean even if all files were immediately deleted upon upload to Amazon S3, the server that handles the HTTP requests still has to do all the audio-video editing. If the number of simultaneous videos being uploaded and edited gets large (100+), I could imagine needing to grow.

**Comment by erikd** [comment]
> The fact that the webapp part has to do audio and video processing

I think that should be batched and queued so it doesn't have to be part of the webapp. Once its batched and queued its easy to scale.

**Comment by JohnReedLOL** [comment]
I guess I could just create a bash script that automatically appends a logo to the beginning of all videos in a directory every 30 seconds and then sends those logo-d files to Amazon s3. I hope Keter and Yesod are ready to handle a potentially enterprise grade application. Thank you.

**Comment by erikd** [comment]
@JohnReedLOL If you are happy with the response you received here, please close this ticket.

**Comment by psibi** [comment]
Closing this issue. Please re-open if relevant.
